# SPDX-License-Identifier: CC-BY-4.0
# Copyright Contributors to the Zowe project.
title: Zowe
description: > # this means to ignore newlines until "keywords:"
  Zowe is an open source framework for leveraging data and applications in z/OS from modern applications and tools
keywords: mainframe, zos, open source, framework
theme: jekyll-theme-cayman
auto_ids: true

# URLs to various sites
latest_video_embed: https://www.youtube.com/embed/7XpOjREP8JU
ibm_ztrial_url: https://www.openmainframeproject.org/projects/zowe/ztrial
github_repo_url: https://github.com/zowe
docs_site_url: https://docs.zowe.org
community_site_url: https://github.com/zowe/community/blob/master/README.md
forums_url: https://community.openmainframeproject.org/c/zowe
slack_url: https://slack.openmainframeproject.org
mailing_list_user_url: https://lists.openmainframeproject.org/g/zowe-user
youtube_zowe_url: https://www.youtube.com/playlist?list=PL8REpLGaY9QE_9d57tw3KQdwSVLKuTpUZ
conformance_page_url: https://www.openmainframeproject.org/projects/zowe/conformance
omp_calendar_url: https://lists.openmainframeproject.org/g/zowe-dev/calendar
zos_download_url: https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/download/legal.html?version=
cli_download_url: https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/download/legal.html?type=cli&version=
cli_plugins_download_url: https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/download/legal.html?type=cli-plugins&version=
cli_active_development_download_url: https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/download/legal.html?type=cli-active-development&version=
smpe_download_url: https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/download/legal.html?type=smpe&version=
zowe_node_sdk_download_url: https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/download/legal.html?type=nodejs-sdk&version=
zowe_python_sdk_download_url: https://zowe.jfrog.io/zowe/list/libs-release-local/org/zowe/download/legal.html?type=python-sdk&version=
nightly_build_url: https://zowe.jfrog.io/zowe/webapp/#/artifacts/browse/tree/General/libs-release-local/org/zowe/nightly
zowe_build_slack_url: https://openmainframeproject.slack.com/archives/CC9QW5NJE
lts_url: https://github.com/zowe/zlc/blob/master/process/ReleaseProcess.md
zowe_fmid: AZWE001
zowe_fmid_oss_version: 1.9.0
zos_component_install_doc_url: https://docs.zowe.org/stable/user-guide/install-zos.html
zowe_cli_install_doc_url: https://docs.zowe.org/stable/user-guide/cli-installcli.html
zowe_explorer_install_doc_url: https://docs.zowe.org/stable/user-guide/ze-install.html
zowe_sdk_install_doc_url: https://docs.zowe.org/stable/user-guide/sdks-using.html
vscode_marketplace_url: https://marketplace.visualstudio.com/items?itemName=Zowe.vscode-extension-for-zowe
zowe_docker_download_url: https://zowe.jfrog.io/zowe/libs-release-local/org/zowe
zowe_dockerhub_download_url: https://hub.docker.com/r/ompzowe/server-bundle
docker_install_doc_url: https://docs.zowe.org/stable/user-guide/install-docker.html
app_framework_doc_url: https://github.com/zowe/docs-site/blob/redesign-nav/docs/getting-started/user-roadmap-app-framework.md
app_framework_github_url: https://github.com/zowe/zlux
apiml_doc_url: https://github.com/zowe/docs-site/blob/redesign-nav/docs/getting-started/user-roadmap-apiml.md
apiml_github_url: https://github.com/zowe/api-layer
zowe_cli_doc_url: https://github.com/zowe/docs-site/blob/redesign-nav/docs/getting-started/user-roadmap-zowe-cli.md
zowe_cli_github_url: https://github.com/zowe/zowe-cli
zowe_explorer_doc_url: https://github.com/zowe/docs-site/blob/redesign-nav/docs/getting-started/user-roadmap-zowe-explorer.md
zowe_explorer_github_url: https://github.com/zowe/vscode-extension-for-zowe
zowe_sdk_doc_url: https://github.com/zowe/docs-site/blob/redesign-nav/docs/getting-started/user-roadmap-client-sdk.md
zowe_sdk_github_url: https://github.com/zowe/zowe-cli
zowe_mobile_doc_url: https://github.com/zowe/docs-site/blob/redesign-nav/docs/getting-started/user-roadmap-zowe-mobile.md
zowe_mobile_github_url: https://github.com/zowe/zowe-on-the-go
zowe_video_deck_url: https://docs.zowe.org/stable/Zowe_introduction_video_deck.pptx
zowe_video_transcript_url: https://docs.zowe.org/stable/Zowe_introduction_video_script.txt
learn_page_get_started: https://github.com/zowe/docs-site/blob/redesign-nav/docs/getting-started/zowe-getting-started.md
zowe_medium_blog_url: https://medium.com/zowe
master_the_mainframe_url: https://www.ibm.com/it-infrastructure/z/education/master-the-mainframe
visual_studio_code_url: https://code.visualstudio.com/
web_dev_node_url: https://nodejs.org/
zowe_extend_doc_url: https://docs.zowe.org/stable/extend/extend-zowe-overview.html
create_zowe_issue_url: https://github.com/zowe/community/issues/new/choose
conformance_step1_url: https://www.openmainframeproject.org/projects/zowe/conformance/terms-and-conditions
conformance_step2_url: https://www.openmainframeproject.org/projects/zowe/conformance/test-evaluation-guide
conformance_step3_url: https://www.openmainframeproject.org/projects/zowe/conformance/participation-form-esign

#TODO add url for zowe_sdk_install_doc_url, zowe_node_sdk_download_url, and zowe_python_sdk_download_url

plugins:
  # Redirect plugin
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - dco_signoffs
  - .gitignore
